<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>QLTB</RootNamespace>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fmDangKy.xaml" />
    <None Remove="fmQuenMatKhau.xaml" />
    <None Remove="MainWindow.xaml" />
    <None Remove="Resource\MainResource.xaml" />
    <None Remove="Resource\SidebarRadioButtonStyle.xaml" />
    <None Remove="Resource\ToggleSwitchStyle.xaml" />
    <None Remove="UserControlFolder\DashBoard\DashBoardView.xaml" />
    <None Remove="UserControlFolder\Device\DeviceFormView.xaml" />
    <None Remove="UserControlFolder\Device\DeviceView.xaml" />
    <None Remove="UserControlFolder\Employee\EmployeeFormView.xaml" />
    <None Remove="UserControlFolder\Employee\EmployeeView.xaml" />
    <None Remove="UserControlFolder\ForgetPass1.xaml" />
    <None Remove="UserControlFolder\ForgetPass2.xaml" />
    <None Remove="UserControlFolder\ForgetPass3.xaml" />
    <None Remove="UserControlFolder\IncidentReport\IncidentReportFormView.xaml" />
    <None Remove="UserControlFolder\IncidentReport\IncidentReportView.xaml" />
    <None Remove="UserControlFolder\Maintenance\MaintenanceHistoryView.xaml" />
    <None Remove="UserControlFolder\Maintenance\MaintenancePlan.xaml" />
    <None Remove="UserControlFolder\Maintenance\MaintenancePlanFormView.xaml" />
    <None Remove="UserControlFolder\Maintenance\MaintenanceTask.xaml" />
    <None Remove="UserControlFolder\Material\MaterialFormView.xaml" />
    <None Remove="UserControlFolder\Material\MaterialView.xaml" />
    <None Remove="UserControlFolder\Setting\SettingMainView.xaml" />
    <None Remove="UserControlFolder\Setting\SettingNotificationView.xaml" />
    <None Remove="UserControlFolder\Setting\SettingProfileView.xaml" />
    <None Remove="UserControlFolder\Setting\SettingSecurityView.xaml" />
    <None Remove="UserControlFolder\Setting\SettingSystemView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="FontAwesome5.WPF" Version="1.0.5" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <Page Include="fmDangKy.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="fmDangNhap.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="fmQuenMatKhau.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\MainResource.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\SidebarRadioButtonStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\ToggleSwitchStyle.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\DashBoard\DashBoardView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Device\DeviceFormView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Device\DeviceView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Employee\EmployeeFormView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Employee\EmployeeView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass3.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\IncidentReport\IncidentReportFormView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\IncidentReport\IncidentReportView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Maintenance\MaintenanceHistoryView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Maintenance\MaintenancePlan.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Maintenance\MaintenancePlanFormView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Maintenance\MaintenanceTask.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Material\MaterialFormView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Material\MaterialView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Setting\SettingMainView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Setting\SettingNotificationView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Setting\SettingProfileView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Setting\SettingSecurityView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\Setting\SettingSystemView.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Update="fmDangNhap.xaml.cs">
      <DependentUpon>fmDangNhap.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Include="Resource\Button.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\ButtonStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\CardStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\ComboBoxStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\DataGridStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\DatePickerStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\InputStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\SBButton.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\TextBox.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\TextBoxStyles.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
