<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>QLTB</RootNamespace>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="fmDangKy.xaml" />
    <None Remove="fmQuenMatKhau.xaml" />
    <None Remove="Resource\MainResource.xaml" />
    <None Remove="UserControlFolder\ForgetPass1.xaml" />
    <None Remove="UserControlFolder\ForgetPass2.xaml" />
    <None Remove="UserControlFolder\ForgetPass3.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <Page Include="fmDangKy.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="fmDangNhap.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Page Include="fmQuenMatKhau.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="Resource\MainResource.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass1.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass2.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Include="UserControlFolder\ForgetPass3.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Compile Update="fmDangNhap.xaml.cs">
      <DependentUpon>fmDangNhap.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
