<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <RootNamespace>QLTB</RootNamespace>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </ApplicationDefinition>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <Page Include="fmDangNhap.xaml">
      <Generator>MSBuild:Compile</Generator>
      <SubType>Designer</SubType>
    </Page>
    <Compile Update="fmDangNhap.xaml.cs">
      <DependentUpon>fmDangNhap.xaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
